global:
  namespaceOverride: ""
connection:
  kaholoUrl: https://mycompany.kaholo.net
  serviceAccountToken: token-123asd
controller:
  image: matankaholo/kubernetes-agents-controller:v6.4.0
  additionalAgentImages: []
  clusterKey: k8s-agents-cluster
  clusterName: k8s-agents-cluster