apiVersion: v1
kind: List
metadata:
  name: kubernetes-agents-controller-resources
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kubernetes-agents-controller
    namespace: {{ include "controller.namespace" . | quote }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kubernetes-agents-controller
    template:
      metadata:
        labels:
          app: kubernetes-agents-controller
      spec:
        serviceAccountName: kubernetes-agents-controller-sa
        containers:
        - name: kubernetes-agents-controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: IfNotPresent
          env:
          - name: SERVER_URL
            value: "{{ .Values.connection.kaholoUrl }}"
          - name: REGISTRATION_TOKEN
            value: "{{ .Values.connection.registrationToken }}"
          - name: CLUSTER_KEY
            value: "{{ .Values.controller.clusterKey }}"
          - name: CLUSTER_NAME
            value: "{{ .Values.controller.clusterName }}"
          - name: NAMESPACE
            value: {{ include "controller.namespace" . | quote }}
          - name: ADDITIONAL_AGENTS_IMAGES
            value: "{{ join "," .Values.controller.additionalAgentImages }}"
