apiVersion: v1
kind: List
metadata:
  name: kubernetes-agents-controller-resources
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kubernetes-agents-controller
    namespace: kaholo-kubernetes-agents-controller
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kubernetes-agents-controller
    template:
      metadata:
        labels:
          app: kubernetes-agents-controller
      spec:
        serviceAccountName: kubernetes-agents-controller-sa
        containers:
        - name: kubernetes-agents-controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: IfNotPresent
          command:
          - "sh"
          - "-c"
          - "./startup.sh"
          env:
          - name: KAHOLO_URL
            value: "{{ .Values.connection.kaholoUrl }}"
          - name: SERVICE_ACCOUNT_TOKEN
            value: "{{ .Values.connection.serviceAccountToken }}"
          - name: ADDITIONAL_AGENTS_IMAGES
            value: "{{ join "," .Values.controller.additionalAgentImages }}"
